### PR TITLE
Add option for custom handler for fatal messages

### PR DESCRIPTION
**Pull request by abeverley**
Hi Mark,

I'd like to add a way for a custom handler to be called when a fatal message occurs. Hopefully the patch says it all, but let me know your feedback.

Thanks, Andy

### CODE REVIEW

**Comment by abeverley** [comment]
Thanks Mark, all those additions look good and improve it.

I was just thinking this morning that it might be better to allow ```fatal_handler``` to be called multiple times, to add a handler each time. Each one would be called in turn, until one returned true, otherwise the default handler should be used. This would have the advantage that different handlers could be set up in different parts of an application. I'll work on a further patch.

**Comment by markov2** [comment]
* Andy Beverley (notifications@github.com) [180413 10:29]:
> Thanks Mark, all those additions look good and improve it.
> 
> I was just thinking this morning that it might be better to allow
> ```fatal_handler``` to be called multiple times, to add a handler
> each time. Each one would be called in turn, until one returned true,
> otherwise the default handler should be used. This would have the
> advantage that different handlers could be set up in different parts of
> an application. I'll work on a further patch.

This is exactly one of the main features of Dancer2 which I dislike
most: the DSL hinders localization of handlers... which you really
want when a website is build from separate components.

I would prefer specifying   "try {} fatal_handler => &fatal;"  a
hundred times over a global fault handler...

Anyways: we have to blend in, and you're the boss over that module
so I will pull the patch once it's fully ready.
-- 
Regards,

               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by abeverley** [comment]
Thanks :)

To be fair, Dancer does have the concept of different apps which can all have different configs for the same plugin, but when you just want something "slightly" different you don't want to run multiple apps (although admittedly I haven't actually tried this to see how well it works).

Anyway, the last patch adds the functionality as previously described.

**Comment by markov2** [comment]
Point is, that during the evolution of a single app, you may want to change the behavior for new components while leaving the older components untouched.  Or: the composition of two components into one.  It just does happen over time.

**Comment by markov2** [comment]
Next time, please add a line to the ChangeLog as well.

**Pull request merged**
